_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  book__render:
    enabled: true
    menu_name: tools
    parent: ''
    expanded: false
    weight: 0
  filter__tips_all:
    enabled: true
    menu_name: tools
    parent: ''
    weight: 0
    expanded: false
  search__view:
    enabled: true
    menu_name: tools
    parent: ''
    weight: 0
    expanded: false
